pipeline {
    agent any
    environment {
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages{
        stage('Clone Repo'){
            steps{
                checkout scm
                sh 'ls *'
            }
        }
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t keshavkumar23022000/jenkins-docker:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Dockerhub Login'){
            steps{
                 
                 sh 'echo DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
            }
        }
        stage('Docker PUSH'){
            steps{
                 
                 sh 'docker push keshavkumar23022000/jenkins-docker:$BUILD_NUMBER'
            }
        }
    }
    post{
        always{
            echo "docker logout"
        }
    }
}  
     
